/*
 * Deployment-specific settings.
 * This is the only file that normally requires an environment-specific edit.
 */
window.HAM_RUNTIME = Object.freeze({
  // Copy the browser key from the current working map into the value below.
  // Restrict the key to the Maps JavaScript API and your GitHub Pages referrers.
  googleMapsApiKey: "AIzaSyBxUzPZYFuNou4HVQlVcrvkIUgHWbGuJd0",

  // Canonical GeoJSON generated by Publisher.gs and uploaded/published for the map.
  dataUrl: "/data/habersham-parcels.geojson",

  defaultProfile: "default",
  googleMapId: "",
  googleLanguage: "en",
  googleRegion: "US",

  // Adds a timestamp query string so GitHub Pages/CDN does not serve stale Deal data.
  cacheBustData: true,

  // Set true only while troubleshooting in the browser console.
  debug: false
});
